[package]
name = "regexp-rust"
version = "0.1.0"
authors = ["Masaki Kamano <kamano.m.aa@m.titech.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
